### ISSUE TITLE
Use platypus

### ISSUE THREAD

**Issue by memlucky71** [pylover/yml2pdf#5]
https://www.reportlab.com/docs/reportlab-userguide.pdf

**Comment by memlucky71** [comment]
@pylover is this new arrangement OK?

**Comment by pylover** [comment]
Why you are using camelCase names for keys?

**Comment by memlucky71** [comment]
@pylover in reportlab ParagraphStyle class, we have : 
```
class ParagraphStyle(PropertySet):
    defaults = {
        'fontName':_baseFontName,
        'fontSize':10,
        'leading':12,
        'leftIndent':0,
        'rightIndent':0,
        'firstLineIndent':0,
        'alignment':TA_LEFT,
        'spaceBefore':0,
        'spaceAfter':0,
        'bulletFontName':_baseFontName,
        'bulletFontSize':10,
        'bulletIndent':0,
        #'bulletColor':black,
        'textColor': black,
        'backColor':None,
```
I wanted to directly override those attributes without creating a mapping for styles. 
Is it better to use snake_case and handle this in our module?

**Comment by pylover** [comment]
http://stackoverflow.com/questions/19053707/converting-snake-case-to-lower-camel-case-lowercamelcase
http://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case

**Comment by memlucky71** [comment]
well, I'll use snake_case. thanks

**Comment by pylover** [comment]
We're never break the rules,
